language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

# command to install dependencies
install:
  - pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox
